
//FISHES
export const ADD_FISHES = 'ADD_FISHES';
export const FISHES_LOADING = "FISHES_LOADING";
export const FISHES_FAILED = "FISHES_FAILED";

//FISH-FOODS
export const ADD_FOODS = "ADD_FOODS";
export const FOODS_LOADING = "FOODS_LOADING";
export const FOODS_FAILED = "FOODS_FAILED";

//SUBSTRATES
export const ADD_SUBSTRATES = "ADD_SUBSTRATES";
export const SUBSTRATES_LOADING = "SUBSTRATES_LOADING";
export const SUBSTRATES_FAILED = "SUBSTRATES_FAILED";

//PLANTS
export const ADD_PLANTS = "ADD_PLANTS";
export const PLANTS_LOADING = "PLANTS_LOADING";
export const PLANTS_FAILED = "PLANTS_FAILED";

//FILTERS
export const ADD_FILTERS = "ADD_FILTERS";
export const FILTERS_LOADING = "FILTERS_LOADING";
export const FILTERS_FAILED = "FILTERS_FAILED";

//RECENTLY ADDED PRODUCTS
export const ADD_RECENT = "ADD_RECENT";
export const RECENT_LOADING = "RECENT_LOADING";
export const RECENT_FAILED = "RECENT_FAILED";

//Products
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const PRODUCTS_FAILED = "PRODUCTS_FAILED";


 //users
export const FIND_USER = "FIND_USER"
export const USER_LOADING = "USER_LOADING"
export const USER_FAILED = "USER_FAILED"

//tickets
export const ADD_TICKETS = "ADD_TICKETS"
export const TICKETS_FAILED = "TICKETS_FAILED"
export const TICKETS_LOADING = "TICKETS_LOADING"